import EasyMDE from 'easymde';

export default [
  {
    name: 'bold',
    action: EasyMDE.toggleBold,
    className: 'fa fa-bold',
    title: 'Bold',
    default: true,
  },
  {
    name: 'italic',
    action: EasyMDE.toggleItalic,
    className: 'fa fa-italic',
    title: 'Italic',
    default: true,
  },
  {
    name: 'heading',
    action: EasyMDE.toggleHeadingSmaller,
    className: 'fa fa-header fa-heading',
    title: 'Heading',
    default: true,
  },
  '|',
  {
    name: 'quote',
    action: EasyMDE.toggleBlockquote,
    className: 'fa fa-quote-left',
    title: 'Quote',
    default: true,
  },
  {
    name: 'unordered-list',
    action: EasyMDE.toggleUnorderedList,
    className: 'fa fa-list-ul',
    title: 'Generic List',
    default: true,
  },
  {
    name: 'ordered-list',
    action: EasyMDE.toggleOrderedList,
    className: 'fa fa-list-ol',
    title: 'Numbered List',
    default: true,
  },
  '|',
  {
    name: 'link',
    action: EasyMDE.drawLink,
    className: 'fa fa-link',
    title: 'Create Link',
    default: true,
  },
  {
    name: 'image',
    action: EasyMDE.drawImage,
    className: 'fa fa-image',
    title: 'Insert Image',
    default: true,
  },
  '|',
  {
    className: 'fa fa-arrows-alt',
    name: 'fullScreen',
    noMobile: false,
    title: 'Toggle Fullscreen',
    action: EasyMDE.toggleFullScreen,
  },
  '|',
  {
    name: 'guide',
    action: 'https://www.markdownguide.org/basic-syntax/',
    className: 'fa fa-question-circle',
    nomobnoDisable: true,
    default: true,
    title: 'Markdown Guide',
  },
  '|',
];
